### ISSUE TITLE
build doesn't work

### ISSUE THREAD

**Issue by microdou** [svelteness/kit-docs#5]
`npm run build` doesn't work.

To reproduce:
```bash
$ npm init @svelteness/kit-docs mydocs
$ npm install

# development works
$ npm run dev

# build doesn't work
$ npm run build
```

The error messages is:
```
[vite]: Rollup failed to resolve import "@docsearch/js" from "node_modules/@svelteness/kit-docs/client/components/algolia/AlgoliaSearch.svelte".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
```

This error can be resolved by adding the following to `vite` setting
```javascript
// svelte.config.js
// under config.kit.vite setting

build: {
  rollupOptions: {
    external: ["@docsearch/js"],
  },
},
```
Now comes the second error:
```
file:///.svelte-kit/output/server/chunks/index-378e2722.js:4052
      const path2 = require("path");
                    ^
ReferenceError: require is not defined
```

**Comment by microdou** [comment]
Adding `@docsearch/js` as dev dependency to `package.json` also resolves the first error. No need to mess up `vite` configuration [😊](https://emojipedia.org/smiling-face-with-smiling-eyes/)

**Comment by mihar-22** [comment]
Working on a fix :)

**Comment by microdou** [comment]
"Well, looks like still broken...

By upgrading `@svelteness/kit-docs` to version `0.4.0` in `package.json`, and run `npm run build`, the following new error occurs:

```
307 / -> /docs/first-category/first-page
> 404 /docs (linked from /docs/first-category/first-page)
    at file:///node_modules/@sveltejs/kit/dist/chunks/index2.js:983:11
    at save (file:///node_modules/@sveltejs/kit/dist/chunks/index2.js:1203:4)
    at visit (file:///node_modules/@sveltejs/kit/dist/chunks/index2.js:1094:3)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by mihar-22** [comment]
New create package adds an `index.svelte` file at `src/routes/docs/index.svelte`: 

```svelte
<script context="module">
  export const prerender = true;
  /** @type {import(["@sveltejs/kit"](https://www.npmjs.com/package/@sveltejs/kit)).Load} */
  export function load() {
    return {
      status: 307,
      redirect: '/docs/first-category/first-page',
    };
  }
</script>
```

Add that and everything will work 😄

**Comment by microdou** [comment]
Oh Yes, just found out independently from the following changes:

https://github.com/svelteness/kit-docs/commit/be052e13030988495a6f0bb186b06657d8d67998

**Comment by microdou** [comment]
Thank you so much! Now it builds perfectly!
