### ISSUE TITLE
What does the config: config.kit.prerender.default in svelte.config.js do?

### ISSUE THREAD

**Issue by jonasfroeller** [svelteness/kit-docs#88]
"config.kit.prerender.default: true" is not a valid setting, or is it?
I don't find it in the docs: https://kit.svelte.dev/docs/configuration#prerender. Is it crawl: true maybe?
I removed it and the app works now.

```bash
C:\Users\Jonas\Downloads\mydocs>npm run dev

> mydocs@0.0.1 dev
> vite dev

error when starting dev server:
Error: Unexpected option config.kit.prerender.default
    at file:///C:/Users/Jonas/Downloads/mydocs/node_modules/@sveltejs/kit/src/core/config/options.js:314:12
    at file:///C:/Users/Jonas/Downloads/mydocs/node_modules/@sveltejs/kit/src/core/config/options.js:321:18
    at file:///C:/Users/Jonas/Downloads/mydocs/node_modules/@sveltejs/kit/src/core/config/options.js:321:18
    at validate_config (file:///C:/Users/Jonas/Downloads/mydocs/node_modules/@sveltejs/kit/src/core/config/index.js:108:9)
    at process_config (file:///C:/Users/Jonas/Downloads/mydocs/node_modules/@sveltejs/kit/src/core/config/index.js:80:20)
    at load_config (file:///C:/Users/Jonas/Downloads/mydocs/node_modules/@sveltejs/kit/src/core/config/index.js:72:9)
    at async sveltekit (file:///C:/Users/Jonas/Downloads/mydocs/node_modules/@sveltejs/kit/src/exports/vite/index.js:119:24)
    at async Promise.all (index 2)
    at async asyncFlatten (file:///C:/Users/Jonas/Downloads/mydocs/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:12623:16)
    at async resolveConfig (file:///C:/Users/Jonas/Downloads/mydocs/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:64022:29)
```

**Comment by DamonMedek** [comment]
I got this problem too. I don't know how to remove it or why its happening. Pretty shotty Demo. I've been messing around this for an hour without anything working.

**Comment by CaptainCodeman** [comment]
It's from an earlier pre-release version of SvelteKit - just delete that line.
